### ISSUE TITLE
crash on add transaction

### ISSUE THREAD

**Issue by cyko69** [chvp/NanoLedger#68]
##### Reproduction steps
Add transaction, fill all fields (2 accounts), save

##### System information
NanoLedger 0.1.4
Redmi Note 5, Android 11
DivestOs 18.1

Logcat

FATAL EXCEPTION: DefaultDispatcher-worker-2
Process: be.chvp.nanoledger, PID: 22807
java.util.NoSuchElementException: List is empty.
	at m3.o.F0(Unknown Source:24)
	at x2.e.a(Unknown Source:92)
	at z2.c0.g(Unknown Source:342)
	at r3.a.c(Unknown Source:8)
	at g4.g0.run(Unknown Source:109)
	at kotlinx.coroutines.internal.f.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.run(Unknown Source:76)
	Suppressed: g4.e0: [n1{Cancelling}@6ee7885, Dispatchers.IO]

**Comment by chvp** [comment]
Sorry about that, should be fixed in 0.1.5.
